- name: Deploy web application
  hosts: db_and_web_server
  become: yes
  tasks:
    - name: Install all required dependncies
      apt: 
        name:
        - python3
        - python3-setuptools
        - python3-dev
        - build-essential
        - python3-pip
        - mysql-server
        - mysql-client
        - python3-mysqldb
        state: present
        autoclean: yes

    - name: without password sudoers
      copy:
        content: '%wheel ALL=(ALL:ALL) NOPASSWD:ALL'
        dest: /etc/sudoers.d/wheel_nopasswd
        mode: 0440

    - name: Starting MySQL
      service:
        name: mysql
        state: started
        enabled: yes       
    - name: Create application database
      mysql_db: name=employee_db state=present
    - name: create database user
      mysql_user:
        name: db_user
        password: passw0rd
        priv: '*.*:ALL'
        state: present
        host: '%'
        login_unix_socket: /var/run/mysqld/mysqld.sock

    - name: Install flask dependencies
      pip:
        name:
         - flask
         - flask-mysql

    - name: Copy file with owner and permissions
      ansible.builtin.copy:
        src: app.py
        dest: /opt/app.py
        mode: '0644'

    - name: Start the web server
      shell: FLASK_APP=/opt/app.py nohup flask run --host=0.0.0.0 &