---
- name: Installing httpd
  hosts: local
  vars:
    package_name: httpd
    file_name: sunil
  
  tasks:
    - name: Package Installing
      yum:
        name: "{{ package_name }}"
        state: present
    - name: Start service
      service:
        name: "{{ package_name }}"
        state: started
    - name: creating files
      file:
        state: touch
        path: /tmp/"{{ file_name }}".txt