---
- name: "Uninstalling httpd"
  hosts: local
  become: yes
  tasks:
    - name: "Unistalling apache"
      yum:
        name: httpd
        state: absent
# ansible-playbook playbook-package.yml -K
# use -K or --ask-become-pass